# Generated by Django 6.0.2 on 2026-04-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerPersonalDetails",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "customer_personal_details",
            },
        ),
        migrations.CreateModel(
            name="CustomerCredentials",
            fields=[
                ("credential_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank.customerpersonaldetails",
                    ),
                ),
            ],
            options={
                "db_table": "customer_credentials",
            },
        ),
        migrations.CreateModel(
            name="CustomerBankDetails",
            fields=[
                ("bank_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                ("ifsc_code", models.CharField(max_length=15)),
                ("branch_name", models.CharField(max_length=100)),
                ("account_type", models.CharField(max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank.customerpersonaldetails",
                    ),
                ),
            ],
            options={
                "db_table": "customer_bank_details",
            },
        ),
    ]
