# Generated by Django 6.0.2 on 2026-04-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerTransactionHistory",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_type", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Bank.customerpersonaldetails",
                    ),
                ),
            ],
            options={
                "db_table": "customer_transaction_history",
            },
        ),
    ]
