# Generated by Django 6.0.2 on 2026-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bank", "0002_customertransactionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertransactionhistory",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
